import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'NextChat',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" data-theme="synthwave">
			<body className={cn(
				"min-h-screen font-sans antialiased grainy",
				inter.className
			)}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
